# Generated by Django 5.1.3 on 2025-01-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, null='true')),
                ('password', models.CharField(default='', max_length=20, null='true')),
                ('confirmpassword', models.CharField(default='', max_length=20, null='true')),
            ],
        ),
    ]
